/* Top level module of the FPGA that takes the onboard resources 
 * as input and outputs the lines drawn from the VGA port.
 *
 * Inputs:
 *   KEY 			- On board keys of the FPGA
 *   SW 			- On board switches of the FPGA
 *   CLOCK_50 		- On board 50 MHz clock of the FPGA
 *
 * Outputs:
 *   HEX 			- On board 7 segment displays of the FPGA
 *   LEDR 			- On board LEDs of the FPGA
 *   VGA_R 			- Red data of the VGA connection
 *   VGA_G 			- Green data of the VGA connection
 *   VGA_B 			- Blue data of the VGA connection
 *   VGA_BLANK_N 	- Blanking interval of the VGA connection
 *   VGA_CLK 		- VGA's clock signal
 *   VGA_HS 		- Horizontal Sync of the VGA connection
 *   VGA_SYNC_N 	- Enable signal for the sync of the VGA connection
 *   VGA_VS 		- Vertical Sync of the VGA connection
 */
module DE1_SoC (HEX0, HEX1, HEX2, HEX3, HEX4, HEX5, KEY, LEDR, SW, CLOCK_50, 
	VGA_R, VGA_G, VGA_B, VGA_BLANK_N, VGA_CLK, VGA_HS, VGA_SYNC_N, VGA_VS);
	
	output logic [6:0] HEX0, HEX1, HEX2, HEX3, HEX4, HEX5;
	output logic [9:0] LEDR;
	input logic [3:0] KEY;
	input logic [9:0] SW;
	input CLOCK_50;
	output [7:0] VGA_R;
	output [7:0] VGA_G;
	output [7:0] VGA_B;
	output VGA_BLANK_N;
	output VGA_CLK;
	output VGA_HS;
	output VGA_SYNC_N;
	output VGA_VS;
	
	assign HEX0 = '1;
	assign HEX1 = '1;
	assign HEX2 = '1;
	assign HEX3 = '1;
	assign HEX4 = '1;
	assign HEX5 = '1;
	
	// SW0 is active-high reset.
	logic reset;
	assign reset = SW[0];
	
	// Endpoints selected by walk_shape
	logic [10:0] x0, y0, x1, y1;
	
	// Pixel generated by line_drawer
	logic [10:0] x, y;
	
	// Pixel sent to VGA_framebuffer
	logic [10:0] fb_x, fb_y;
	
	// Clear-screen counters
	logic [10:0] clear_x, clear_y;
	
	// VGA write controls
	logic pixel_color;
	logic pixel_write;
	logic invert_mode;
	
	// line_drawer control/status
	logic line_reset;
	logic line_done;
	
	// Animation registers
	logic [4:0] line_num;
	logic [22:0] wait_count;
	logic [2:0] delay;
	logic [10:0] base_x, base_y;
	logic update_en;
	logic frame_num;
	
	// Walking figure has lines 0 through 11
	localparam logic [4:0] LAST_LINE = 5'd11;
	
	// Pause after the full object is drawn
	localparam logic [22:0] WAIT_MAX = 23'd2_500_000;
	
	// Top-level animation states
	typedef enum logic [2:0] {S_CLEAR, S_LINE_RESET, S_DRAW_LINE, S_WAIT, S_UPDATE_POS} state_t;
	state_t ps;
	
	// Reset line_drawer before drawing each new line
	assign line_reset = reset || (ps == S_LINE_RESET);
	
	// Enable position/frame update in S_UPDATE_POS
	assign update_en = (ps == S_UPDATE_POS);
	
	// Choose what the framebuffer receives
	always_comb begin
		if (ps == S_CLEAR) begin
			// Clear screen by writing the background color to each pixel
			fb_x = clear_x;
			fb_y = clear_y;
			pixel_color = invert_mode ? 1'b1 : 1'b0;
			pixel_write = 1'b1;
		end else begin
			// Draw the current line using the opposite color
			fb_x = x;
			fb_y = y;
			pixel_color = invert_mode ? 1'b0 : 1'b1;
			pixel_write = (ps == S_DRAW_LINE) && (delay == 3'd3) && !line_done;
		end
	end
	
	VGA_framebuffer fb (
		.clk50			(CLOCK_50), 
		.reset			(1'b0), 
		.x              (fb_x), 
		.y              (fb_y),
		.pixel_color	(pixel_color), 
		.pixel_write	(pixel_write),
		.VGA_R, 
		.VGA_G, 
		.VGA_B, 
		.VGA_CLK, 
		.VGA_HS, 
		.VGA_VS,
		.VGA_BLANK_n	(VGA_BLANK_N), 
		.VGA_SYNC_n		(VGA_SYNC_N)
	);
	
	// This module updates the walking figure position and frame
	update_pos pos (
		.clk       (CLOCK_50),
		.reset     (reset),
		.update_en (update_en),
		.base_x    (base_x),
		.base_y    (base_y),
		.frame_num (frame_num)
	);
	
	// This module chooses the endpoints of the walking figure line
	walk_shape object (
		.line_num  (line_num),
		.frame_num (frame_num),
		.base_x    (base_x),
		.base_y    (base_y),
		.x0        (x0),
		.y0        (y0),
		.x1        (x1),
		.y1        (y1)
	);
	
	// This module draws one selected line
	line_drawer lines (
		.clk   (CLOCK_50), 
		.reset (line_reset),
		.x0    (x0), 
		.y0    (y0), 
		.x1    (x1), 
		.y1    (y1), 
		.x     (x), 
		.y     (y), 
		.done  (line_done)
	);
	
	
	// Main animation controller
	always_ff @(posedge CLOCK_50) begin
		if (reset) begin
			ps <= S_CLEAR;
			clear_x <= 11'd0;
			clear_y <= 11'd0;
			line_num <= 5'd0;
			wait_count <= 23'd0;
			delay <= 3'd0;
			invert_mode <= 1'b0;
		end else begin
			case (ps)
			
				// Clear the screen by writing background color to every pixel
				S_CLEAR: begin
					if (clear_x == 11'd639) begin
						if (clear_y == 11'd479) begin
							clear_x <= 11'd0;
							clear_y <= 11'd0;
							line_num <= 5'd0;
							ps <= S_LINE_RESET;
						end else begin
							clear_x <= 11'd0;
							clear_y <= clear_y + 11'd1;
						end
					end else begin
						clear_x <= clear_x + 11'd1;
					end
				end
				
				// Give line_drawer a one-clock reset pulse
				S_LINE_RESET: begin
					delay <= 3'd0;
					ps <= S_DRAW_LINE;
				end
				
				// Draw one line of the object
				S_DRAW_LINE: begin
				
					if (delay != 3'd3) begin // Wait for line_drawer setup states 
						delay <= delay + 3'd1;
					end
					
					else if (line_done) begin
						if (line_num == LAST_LINE) begin
							wait_count <= 23'd0;
							ps <= S_WAIT;
						end else begin
							line_num <= line_num + 5'd1;
							ps <= S_LINE_RESET;
						end
					end // END ELSE IF
					// if delay == 3'd3 and line_done == 0, do nothing
					
				end // END S_DRAW_LINE
				
				// Pause so the object is visible
				S_WAIT: begin
					if (wait_count == WAIT_MAX) begin
						wait_count <= 23'd0;
						ps <= S_UPDATE_POS;
					end else begin
						wait_count <= wait_count + 23'd1;
					end
				end
				
				// Update position/frame, then clear and redraw the next frame
				S_UPDATE_POS: begin
					invert_mode <= ~invert_mode;
					clear_x <= 11'd0;
					clear_y <= 11'd0;
					line_num <= 5'd0;
					ps <= S_CLEAR;
				end
				
				default: begin
					ps <= S_CLEAR;
				end
			endcase
		end
	end
	
endmodule