/* Top level module of the FPGA that takes the onboard resources 
 * as input and outputs the lines drawn from the VGA port.
 *
 * Inputs:
 * KEY 			- On board keys of the FPGA
 * SW 			- On board switches of the FPGA
 * CLOCK_50 		- On board 50 MHz clock of the FPGA
 *
 * Outputs:
 * HEX 			- On board 7 segment displays of the FPGA
 * LEDR 			- On board LEDs of the FPGA
 * VGA_R 			- Red data of the VGA connection
 * VGA_G 			- Green data of the VGA connection
 * VGA_B 			- Blue data of the VGA connection
 * VGA_BLANK_N 	- Blanking interval of the VGA connection
 * VGA_CLK 		- VGA's clock signal
 * VGA_HS 		- Horizontal Sync of the VGA connection
 * VGA_SYNC_N 	- Enable signal for the sync of the VGA connection
 * VGA_VS 		- Vertical Sync of the VGA connection
 */
module DE1_SoC (HEX0, HEX1, HEX2, HEX3, HEX4, HEX5, KEY, LEDR, SW, CLOCK_50, 
	VGA_R, VGA_G, VGA_B, VGA_BLANK_N, VGA_CLK, VGA_HS, VGA_SYNC_N, VGA_VS);
    
	output logic [6:0] HEX0, HEX1, HEX2, HEX3, HEX4, HEX5;
	output logic [9:0] LEDR;
	input logic [3:0] KEY;
	input logic [9:0] SW;
	input CLOCK_50;
	output [7:0] VGA_R;
	output [7:0] VGA_G;
	output [7:0] VGA_B;
	output VGA_BLANK_N;
	output VGA_CLK;
	output VGA_HS;
	output VGA_SYNC_N;
	output VGA_VS;
	
	assign HEX0 = '1;
	assign HEX1 = '1;
	assign HEX2 = '1;
	assign HEX3 = '1;
	assign HEX4 = '1;
	assign HEX5 = '1;
	
	// SW0 = reset
	logic reset;
	assign reset = SW[0];
	
	// Endpoints
	logic [10:0] x0, y0, x1, y1;
	logic [10:0] bx0, by0, bx1, by1;
	
	// Wires to feed into line_drawer
	logic [10:0] draw_x0, draw_y0, draw_x1, draw_y1;
	
	// Pixel generated by line_drawer
	logic [10:0] x, y;
	
	// Pixel sent to VGA_framebuffer
	logic [10:0] fb_x, fb_y;
	
	// Clear-screen counters
	logic [10:0] clear_x, clear_y;
	
	// VGA write controls
	logic pixel_color;
	logic pixel_write;
	logic invert_mode;
	
	// line_drawer control and status signals
	logic line_reset;
	logic line_done;
	
	// Animation registers
	logic [4:0] line_num;
	logic [22:0] wait_count;
	logic [2:0] delay;
	logic [10:0] base_x, base_y;
	logic update_en;
	logic frame_num;
	
	// Walking figure has lines 0 through 11
	localparam logic [4:0] LAST_LINE = 5'd11;
	// Pause after the full object is drawn
	localparam logic [22:0] WAIT_MAX = 23'd2_500_000;
	// 2 second wait @ 50MHz
	localparam logic [26:0] TWO_SEC_WAIT = 27'd100_000_000;
	
	// Top-level animation states
	typedef enum logic [3:0] {
		S_CLEAR, S_LINE_RESET, S_DRAW_LINE, S_WAIT, S_UPDATE_POS, 
		
		S_BLACKOUT_CLEAR_1, S_BLACKOUT_HOLD_1, 
		S_BIG_RESET, S_BIG_DRAW, S_BIG_HOLD, 
		S_BLACKOUT_CLEAR_2, S_BLACKOUT_HOLD_2
	} state_t;
	state_t ps;
	
	logic [7:0] cycle_count;           // Counts 0 to 100 for normal animation loops
	logic [26:0] long_wait_count;      // Holds the 2-second delay
	logic is_big_human; 
	
	// Reset line_drawer before drawing each new line
	assign line_reset = reset || (ps == S_LINE_RESET) || (ps == S_BIG_RESET);
	
	// Enable position/frame update in S_UPDATE_POS
	assign update_en = (ps == S_UPDATE_POS);
	
	// Mux to choose between standard animation lines and big human lines
	assign is_big_human = (ps == S_BIG_RESET || ps == S_BIG_DRAW);
	assign draw_x0 = is_big_human ? bx0 : x0; 
	assign draw_y0 = is_big_human ? by0 : y0;
	assign draw_x1 = is_big_human ? bx1 : x1;
	assign draw_y1 = is_big_human ? by1 : y1;
	
	// Choose what the framebuffer receives
	always_comb begin
		if (ps == S_CLEAR) begin
			// Clear screen by writing the background color to each pixel
			fb_x = clear_x; fb_y = clear_y;
			pixel_color = invert_mode ? 1'b1 : 1'b0;
			pixel_write = 1'b1;
		end else if (ps == S_BLACKOUT_CLEAR_1 || ps == S_BLACKOUT_CLEAR_2) begin
			// Force the screen to be black
			fb_x = clear_x; fb_y = clear_y;
			pixel_color = 1'b0; 
			pixel_write = 1'b1;
		end else begin
			fb_x = x; fb_y = y;
			// Big human is always white (1), otherwise use invert logic
			pixel_color = is_big_human ? 1'b1 : (invert_mode ? 1'b0 : 1'b1);
			pixel_write = ((ps == S_DRAW_LINE) || (ps == S_BIG_DRAW)) && (delay == 3'd3) && !line_done;
		end
	end
	
	VGA_framebuffer fb (
		.clk50			(CLOCK_50), 
		.reset			(1'b0), 
		.x              (fb_x), 
		.y              (fb_y),
		.pixel_color	(pixel_color), 
		.pixel_write	(pixel_write),
		.VGA_R, 
		.VGA_G, 
		.VGA_B, 
		.VGA_CLK, 
		.VGA_HS, 
		.VGA_VS,
		.VGA_BLANK_n	(VGA_BLANK_N), 
		.VGA_SYNC_n		(VGA_SYNC_N)
	);
	
	// Reset the walker position after the second blackout ends
	logic pos_reset;
	assign pos_reset = reset || (ps == S_BLACKOUT_HOLD_2);

	// This module updates the walking figure position and frame
	update_pos pos (
		.clk       (CLOCK_50),
		.reset     (pos_reset),
		.update_en (update_en),
		.base_x    (base_x),
		.base_y    (base_y),
		.frame_num (frame_num)
	);
	
	// This module chooses the endpoints of the walking figure line
	walk_shape object (
		.line_num  (line_num),
		.frame_num (frame_num),
		.base_x    (base_x),
		.base_y    (base_y),
		.x0        (x0),
		.y0        (y0),
		.x1        (x1),
		.y1        (y1)
	);
	
	// A static big human shape
	big_human_shape big_human (
		.line_num  (line_num),
		.x0        (bx0),
		.y0        (by0),
		.x1        (bx1),
		.y1        (by1)
	);
	
	// This module draws one selected line
	line_drawer lines (
		.clk   (CLOCK_50), 
		.reset (line_reset),
		.x0    (draw_x0), 
		.y0    (draw_y0), 
		.x1    (draw_x1), 
		.y1    (draw_y1), 
		.x     (x), 
		.y     (y), 
		.done  (line_done)
	);
	
	// Main animation controller FSM
	always_ff @(posedge CLOCK_50) begin
		if (reset) begin
			ps <= S_CLEAR;
			clear_x <= 11'd0; clear_y <= 11'd0;
			line_num <= 5'd0;
			wait_count <= 23'd0;
			long_wait_count <= 27'd0;
			delay <= 3'd0;
			invert_mode <= 1'b0;
			cycle_count <= 8'd0;
		end else begin
			case (ps)
			
				// animation loop
				S_CLEAR: begin
					if (clear_x == 11'd639 && clear_y == 11'd479) begin
						clear_x <= 11'd0; clear_y <= 11'd0;
						line_num <= 5'd0;
						ps <= S_LINE_RESET;
					end else if (clear_x == 11'd639) begin
						clear_x <= 11'd0; clear_y <= clear_y + 11'd1;
					end else begin
						clear_x <= clear_x + 11'd1;
					end
				end // end S_CLEAR
				
				S_LINE_RESET: begin
					delay <= 3'd0;
					ps <= S_DRAW_LINE;
				end // end S_LINE_RESET
				
				S_DRAW_LINE: begin
					if (delay != 3'd3) delay <= delay + 3'd1;
					else if (line_done) begin
						if (line_num == LAST_LINE) begin
							wait_count <= 23'd0;
							ps <= S_WAIT;
						end else begin
							line_num <= line_num + 5'd1;
							ps <= S_LINE_RESET;
						end
					end
				end // end S_DRAW_LINE
				
				S_WAIT: begin
					if (wait_count == WAIT_MAX) begin
						wait_count <= 23'd0;
						ps <= S_UPDATE_POS;
					end else begin
						wait_count <= wait_count + 23'd1;
					end
				end // end S_WAIT
				
				S_UPDATE_POS: begin
					invert_mode <= ~invert_mode;
					clear_x <= 11'd0; clear_y <= 11'd0;
					line_num <= 5'd0;
					
					// Branch off to blackout if 15 cycles hit
					if (cycle_count == 8'd100) begin
						cycle_count <= 8'd0;
						ps <= S_BLACKOUT_CLEAR_1;
					end else begin
						cycle_count <= cycle_count + 10'd1;
						ps <= S_CLEAR;
					end
				end // end S_UPDATE_POS
				
				// all black for some seconds
				S_BLACKOUT_CLEAR_1: begin
					if (clear_x == 11'd639 && clear_y == 11'd479) begin
						clear_x <= 11'd0; clear_y <= 11'd0;
						long_wait_count <= 27'd0;
						ps <= S_BLACKOUT_HOLD_1;
					end else if (clear_x == 11'd639) begin
						clear_x <= 11'd0; clear_y <= clear_y + 11'd1;
					end else begin
						clear_x <= clear_x + 11'd1;
					end
				end // end S_BLACKOUT_CLEAR_1
				
				S_BLACKOUT_HOLD_1: begin
					if (long_wait_count == TWO_SEC_WAIT) begin
						long_wait_count <= 27'd0;
						line_num <= 5'd0;
						ps <= S_BIG_RESET;
					end else begin
						long_wait_count <= long_wait_count + 27'd1;
					end
				end // end S_BLACKOUT_HOLD_1

				// BIG HUMAN EVENT
				S_BIG_RESET: begin
					delay <= 3'd0;
					ps <= S_BIG_DRAW;
				end // end S_BIG_RESET
				
				S_BIG_DRAW: begin
					if (delay != 3'd3) delay <= delay + 3'd1;
					else if (line_done) begin
						if (line_num == 5'd21) begin // 21 lines (0-10) for big human and start
							long_wait_count <= 27'd0;
							ps <= S_BIG_HOLD;
						end else begin
							line_num <= line_num + 5'd1;
							ps <= S_BIG_RESET;
						end
					end
				end // end S_BIG_DRAW
				
				S_BIG_HOLD: begin
					if (long_wait_count == TWO_SEC_WAIT) begin
						long_wait_count <= 27'd0;
						clear_x <= 11'd0; clear_y <= 11'd0;
						ps <= S_BLACKOUT_CLEAR_2;
					end else begin
						long_wait_count <= long_wait_count + 27'd1;
					end
				end // end S_BIG_HOLD

				// BLACKOUT 2
				S_BLACKOUT_CLEAR_2: begin
					if (clear_x == 11'd639 && clear_y == 11'd479) begin
						clear_x <= 11'd0; clear_y <= 11'd0;
						long_wait_count <= 27'd0;
						ps <= S_BLACKOUT_HOLD_2;
					end else if (clear_x == 11'd639) begin
						clear_x <= 11'd0; clear_y <= clear_y + 11'd1;
					end else begin
						clear_x <= clear_x + 11'd1;
					end
				end // end S_BLACKOUT_CLEAR_2
				
				S_BLACKOUT_HOLD_2: begin
					if (long_wait_count == TWO_SEC_WAIT) begin
						long_wait_count <= 27'd0;
						invert_mode <= 1'b0; // Reset normal phase mapping
						ps <= S_CLEAR;       // Restart animation
					end else begin
						long_wait_count <= long_wait_count + 27'd1;
					end
				end // end S_BLACKOUT_HOLD_2
				
				default: ps <= S_CLEAR;
			endcase
		end
	end
	
endmodule // END DE1